apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: mojaloop
    meta.helm.sh/release-namespace: ml-app
  creationTimestamp: "2021-01-13T09:22:47Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: mojaloop
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: centralledger-handler-transfer-prepare
    app.kubernetes.io/version: 11.3.1
    helm.sh/chart: centralledger-handler-transfer-prepare-11.0.0
  name: mojaloop-centralledger-handler-transfer-prepare
  namespace: ml-app
  resourceVersion: "4696048"
  selfLink: /apis/apps/v1/namespaces/ml-app/deployments/mojaloop-centralledger-handler-transfer-prepare
  uid: 2da2e27d-efba-46dc-86df-3b51dcc4f2e5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: mojaloop
      app.kubernetes.io/name: centralledger-handler-transfer-prepare
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "3001"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mojaloop
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: centralledger-handler-transfer-prepare
        app.kubernetes.io/version: 11.3.1
        helm.sh/chart: centralledger-handler-transfer-prepare-11.0.0
    spec:
      containers:
      - command:
        - node
        - src/handlers/index.js
        - handler
        - --prepare
        env:
        - name: LOG_LEVEL
          value: info
        - name: LOG_FILTER
          value: error, warn, info
        - name: CSL_LOG_TRANSPORT
          value: file
        - name: EVENT_SDK_LOG_FILTER
          value: audit:*, log:warn, log:error
        - name: EVENT_SDK_LOG_METADATA_ONLY
          value: "false"
        - name: EVENT_SDK_SIDECAR_DISABLED
          value: "false"
        - name: EVENT_SDK_SERVER_HOST
          value: localhost
        - name: EVENT_SDK_SERVER_PORT
          value: "50051"
        - name: EVENT_SDK_VENDOR_PREFIX
          value: mojaloop
        - name: EVENT_SDK_TRACESTATE_HEADER_ENABLED
          value: "true"
        - name: EVENT_SDK_ASYNC_OVERRIDE_EVENTS
          value: log,trace
        - name: EVENT_SDK_TRACEID_PER_VENDOR
          value: "false"
        - name: LIB_RESOURCE_VERSIONS
          value: transfers=1.0,participants=1.0,quotes=1.0
        image: mojaloop/central-ledger:v11.3.1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        name: centralledger-handler-transfer-prepare
        ports:
        - containerPort: 3001
          name: http-api
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/central-ledger/config
          name: mojaloop-centralledger-handler-transfer-prepare-config-volume
      - command:
        - npm
        - run
        - start
        env:
        - name: LOG_LEVEL
          value: info
        - name: LOG_FILTER
          value: error, warn, info
        - name: EVENT_SDK_LOG_FILTER
          value: audit:*, log:info, log:warn, log:error
        - name: EVENT_SDK_LOG_METADATA_ONLY
          value: "true"
        image: mojaloop/event-sidecar:v9.5.1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 4001
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        name: centralledger-handler-transfer-prepare-sidecar
        ports:
        - containerPort: 4001
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 4001
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/event-sidecar/config
          name: mojaloop-centralledger-handler-transfer-prepare-sidecar-volume
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - until result=$(mysql -h mojaloop-centralledger-mysql -P 3306 -u central_ledger
          --password=oyMxgZChuu  central_ledger -ss -N -e 'select is_locked from migration_lock;')
          && eval 'echo is_locked=$result' && if [ -z $result ]; then false; fi &&
          if [ $result -ne 0 ]; then false; fi; do echo waiting for MySQL; sleep 2;
          done;
        image: mysql:latest
        imagePullPolicy: Always
        name: wait-for-mysql
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - sh
        - -c
        - until ./bin/kafka-broker-api-versions.sh --bootstrap-server mojaloop-kafka:9092;
          do echo waiting for Kafka; sleep 2; done;
        image: solsson/kafka:latest
        imagePullPolicy: Always
        name: wait-for-kafka
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: default.json
            path: default.json
          - key: knexfile.js
            path: knexfile.js
          name: mojaloop-centralledger-handler-transfer-prepare-config
        name: mojaloop-centralledger-handler-transfer-prepare-config-volume
      - configMap:
          defaultMode: 420
          items:
          - key: default.json
            path: default.json
          name: mojaloop-centralledger-handler-transfer-prepare-sidecar
        name: mojaloop-centralledger-handler-transfer-prepare-sidecar-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-01-13T09:27:34Z"
    lastUpdateTime: "2021-01-13T09:27:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-13T09:22:55Z"
    lastUpdateTime: "2021-01-13T09:27:34Z"
    message: ReplicaSet "mojaloop-centralledger-handler-transfer-prepare-6d796659"
      has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
