apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-portal
  labels:
    app: dev-portal
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # exeed the replicas by 1 pod
  selector:
    matchLabels:
      app: dev-portal
  template:
    metadata:
      labels:
        app: dev-portal
    spec:
      containers:
        - name: dev-portal
          image: lewisdaly/dev-portal:latest
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /
              port: 5000
          readinessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /
              port: 5000
          # env:
          #   - name: DFSP_ID
          #     value: {{ $participantId }}
          #   - name: OUTBOUND_ENDPOINT
          #     value: http://{{ $participantId }}-sdk-scheme-adapter:4001
          #   - name: THIRDPARTY_OUTBOUND_ENDPOINT
          #     value: http://{{ $participantId }}-thirdparty-scheme-adapter:4005
          #   - name: HTTPS_ENABLED
          #     value: 'false'
          #   - name: MUTUAL_TLS_ENABLED
          #     value: 'false'

---
apiVersion: v1
kind: Service
metadata:
  name: dev-portal
spec:
  ports:
    - port: 5000
      name: ui
  selector:
    app: dev-portal
  clusterIP: None
---

# apiVersion: configuration.konghq.com/v1
# kind: KongPlugin
# metadata:
#   name: fspiop-rewrite
# config:
#   add:
#     headers:
#       - x-new-header:newvalue
#   replace:
#     uri: "/$(uri_captures[1])"
#     # uri: "/health"
# plugin: request-transformer
---
# Ingresses for Kong API Gateway to talk to the FSPIOP API
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-portal
  annotations:
    kubernetes.io/ingress.class: kong
    # konghq.com/strip-path: "true"
    # This is required to rewrite paths to services that contain multiple endpoints, 
    # e.g. /participants and /parties are both on the account-lookup-service
    # konghq.com/plugins: fspiop-rewrite
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: dev-portal
              servicePort: 5000
---