
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: fspiop-rewrite
config:
  add:
    headers:
      - x-new-header:newvalue
  replace:
    uri: "/$(uri_captures[1])"
    # uri: "/health"
plugin: request-transformer
---
# Ingresses for Kong API Gateway to talk to the FSPIOP API
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fspiop
  annotations:
    kubernetes.io/ingress.class: kong
    # konghq.com/strip-path: "true"
    # This is required to rewrite paths to services that contain multiple endpoints, 
    # e.g. /participants and /parties are both on the account-lookup-service
    konghq.com/plugins: fspiop-rewrite
spec:
  rules:
    - http:
        paths:
          - path: /api/fspiop/(participants.*)
            backend:
              serviceName: mojaloop-account-lookup-service
              servicePort: 80
          - path: /api/fspiop/(parties.*)
            backend:
              serviceName: mojaloop-account-lookup-service
              servicePort: 80
          - path: /api/fspiop/(transactionRequests.*)
            backend:
              serviceName: mojaloop-transaction-requests-service
              servicePort: 80
          - path: /api/fspiop/(authorizations.*)
            backend:
              serviceName: mojaloop-transaction-requests-service
              servicePort: 80
          - path: /api/fspiop/(quotes.*)
            backend:
              serviceName: mojaloop-quoting-service
              servicePort: 80
          - path: /api/fspiop/(transfers.*)
            backend:
              serviceName: mojaloop-ml-api-adapter-service
              servicePort: 80
          # Example - for testing out rewrite rules
          - path: /api/bar/(participants.*)
            backend:
              serviceName: echo
              servicePort: 80
---
# expose health checks for each endpoint
# note: I'm aware that there are duplicates here, but that's ok
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: fspiop-rewrite-health
config:
  add:
    headers:
      - x-new-header:newvalue
  replace:
    uri: "/health"
plugin: request-transformer
---
# Ingresses for Kong API Gateway to talk to the FSPIOP API
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fspiop
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: fspiop-rewrite-health
spec:
  rules:
    - http:
        paths:
          - path: /api/admin/participants/health
            backend:
              serviceName: mojaloop-account-lookup-service
              servicePort: 80
          - path: /api/admin/parties/health
            backend:
              serviceName: mojaloop-account-lookup-service
              servicePort: 80
          - path: /api/admin/transactionRequests/health
            backend:
              serviceName: mojaloop-transaction-requests-service
              servicePort: 80
          - path: /api/admin/authorizations/health
            backend:
              serviceName: mojaloop-transaction-requests-service
              servicePort: 80
          - path: /api/admin/quotes/health
            backend:
              serviceName: mojaloop-quoting-service
              servicePort: 80
          - path: /api/admin/transfers/health
            backend:
              serviceName: mojaloop-ml-api-adapter-service
              servicePort: 80