# Ingresses for Kong API Gateway to talk to the Admin APIs

apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: admin-rewrite
config:
  add:
    headers:
      - x-new-header:newvalue
  replace:
    uri: "/$(uri_captures[1])"
plugin: request-transformer
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: user123
  annotations:
    kubernetes.io/ingress.class: kong
username: harry 
credentials:
  - harry-basicauth
---
apiVersion: v1
kind: Secret
metadata:
  name: user123-key
stringData:
  username: user123
  kongCredType: basic-auth
  password: OpenSesame
---
# KongPlugin for basic auth - for the demo we can just configure this manually and provide to users
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: basic-auth-example
# config: 
  # hide_credentials: false
  # consumers:
    # - username: user123
    # - username: user456
  # basicauth_credentials:
  #   - consumer: user123
  #     username: Aladdin
  #     password: OpenSesame
plugin: basic-auth
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: admin
  annotations:
    kubernetes.io/ingress.class: kong
    # konghq.com/strip-path: "true"
    # This is required to rewrite paths to services that contain multiple endpoints, 
    # e.g. /participants and /parties are both on the account-lookup-service
    konghq.com/plugins: admin-rewrite, basic-auth-example
    # enable basic auth for these routes
    # konghq.com/plugins: basic-auth-example
spec:
  rules:
    - http:
        paths:
          - path: /api/admin/central-ledger/(.*)
            backend:
              serviceName: mojaloop-centralledger-service
              servicePort: 80
          - path: /api/admin/account-lookup-service/(.*)
            backend:
              serviceName: mojaloop-account-lookup-service
              servicePort: 80
          - path: /api/admin/account-lookup-service-admin/(.*)
            backend:
              serviceName: mojaloop-account-lookup-service-admin
              servicePort: 80
          # todo: this isn't currently working
          # - path: /api/admin/dashboard/(.*)
          - path: /admin/dashboard
            backend:
              serviceName: kubernetes-dashboard
              servicePort: 443
         