# Ingresses for Kong API Gateway to talk to the Admin APIs

apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ttk-rewrite
config:
  replace:
    uri: "/$(uri_captures[1])"
plugin: request-transformer
---
apiVersion: extensions/v1beta1 
kind: Ingress
metadata:
  name: ttk
  annotations:
    kubernetes.io/ingress.class: kong
    # konghq.com/strip-path: "true"
    # This is required to rewrite paths to services that contain multiple endpoints, 
    # e.g. /participants and /parties are both on the account-lookup-service
    konghq.com/plugins: ttk-rewrite
spec:
  rules:
    - host: ttk.beta.moja-lab.live
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: ttk-ml-testing-toolkit-frontend
              servicePort: 6060
    - host: ttk-backend-1.beta.moja-lab.live
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: ttk-ml-testing-toolkit-backend
              servicePort: 5000
    - host: ttk-backend-2.beta.moja-lab.live
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: ttk-ml-testing-toolkit-backend
              servicePort: 5050